SELECT
  CAST(year AS INT) AS year, CAST(month AS INT) AS month, reporting_airline,
  COUNT(*) AS total_flights,
  SUM(CASE WHEN cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS operated_flights,
  SUM(CASE WHEN cancelled = 1 THEN 1 ELSE 0 END) AS cancelled_flights,
  SUM(CASE WHEN diverted = 1 THEN 1 ELSE 0 END) AS diverted_flights,
  SUM(CASE WHEN arrdelay <= 15 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS on_time_flights,
  ROUND(100.0 * SUM(CASE WHEN arrdelay <= 15 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END), 0), 2) AS on_time_pct,
  ROUND(100.0 * SUM(CASE WHEN cancelled = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS cancellation_rate,
  ROUND(100.0 * SUM(CASE WHEN cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) / COUNT(*), 2) AS completion_factor,
  ROUND(AVG(CASE WHEN cancelled = 0 THEN depdelay END), 2) AS avg_dep_delay_min,
  ROUND(AVG(CASE WHEN cancelled = 0 THEN arrdelay END), 2) AS avg_arr_delay_min,
  ROUND(PERCENTILE_APPROX(CASE WHEN cancelled = 0 AND diverted = 0 THEN arrdelay END, 0.50), 2) AS p50_arr_delay_min,
  ROUND(PERCENTILE_APPROX(CASE WHEN cancelled = 0 AND diverted = 0 THEN arrdelay END, 0.90), 2) AS p90_arr_delay_min,
  SUM(CASE WHEN arrdelay <= 0 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS flights_early_or_ontime,
  SUM(CASE WHEN arrdelay > 0 AND arrdelay <= 15 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS flights_delayed_1_to_15,
  SUM(CASE WHEN arrdelay > 15 AND arrdelay <= 60 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS flights_delayed_16_to_60,
  SUM(CASE WHEN arrdelay > 60 AND arrdelay <= 120 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS flights_delayed_61_to_120,
  SUM(CASE WHEN arrdelay > 120 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS flights_delayed_over_120,
  ROUND(AVG(CASE WHEN cancelled = 0 THEN taxiout END), 2) AS avg_taxi_out_min,
  ROUND(AVG(CASE WHEN cancelled = 0 THEN taxiin END), 2) AS avg_taxi_in_min,
  ROUND(AVG(CASE WHEN cancelled = 0 THEN airtime END), 2) AS avg_airtime_min,
  ROUND(AVG(CASE WHEN cancelled = 0 THEN distance END), 2) AS avg_distance_miles,
  ROUND(SUM(CASE WHEN cancelled = 0 THEN distance ELSE 0 END), 0) AS total_miles_flown,
  SUM(CASE WHEN distance < 500 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS operated_short_haul,
  SUM(CASE WHEN distance >= 500 AND distance < 1500 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS operated_medium_haul,
  SUM(CASE WHEN distance >= 1500 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) AS operated_long_haul,
  ROUND(100.0 * SUM(CASE WHEN distance < 500 AND arrdelay <= 15 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN distance < 500 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END), 0), 2) AS otp_short_haul,
  ROUND(100.0 * SUM(CASE WHEN distance >= 500 AND distance < 1500 AND arrdelay <= 15 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN distance >= 500 AND distance < 1500 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END), 0), 2) AS otp_medium_haul,
  ROUND(100.0 * SUM(CASE WHEN distance >= 1500 AND arrdelay <= 15 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN distance >= 1500 AND cancelled = 0 AND diverted = 0 THEN 1 ELSE 0 END), 0), 2) AS otp_long_haul
FROM meridian.silver.silver_flights_clean
GROUP BY year, month, reporting_airline
